Feat/morpho is borrowing any
PeggyJV/cellar-contracts pull request #123
Opened 2023-06-15 16:31 UTC by crispymangoes

2023-06-15 17:13 UTC, 0xEinCodes approved these changes
Looks good to me, changes have been discussed with Auditor as well. The only thing I might ask for is to add a couple of lines in the main PR message here of what the intent of this PR is for future reference.

2023-06-15 23:47 UTC, kingofclubstroyDev commented on src/modules/adaptors/Morpho/MorphoAaveV2ATokenAdaptor.sol
>       */
This natSpec comment is not longer accurate

2023-06-16 14:26 UTC, 0xEinCodes commented on src/modules/adaptors/Morpho/MorphoAaveV2ATokenAdaptor.sol
> +    function withdrawableFrom(bytes memory adaptorData, bytes memory) public view override returns (uint256) {
@kingofclubstroyDev comment is right. Also please add params descriptions.

2023-06-16 14:28 UTC, 0xEinCodes requested changes
Looks good to me other than one change request on nat spec. You can address that with the other fixes from the audit. :)

2023-06-16 16:14 UTC, merged